kete_hs21/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard', views.dashboard, name="dashboard"),
    path('welcome', views.welcome, name="welcome"),
    path('about', views.about, name="about"),
    path('prototype_student', views.prototype_student, name="prototype_student"),
    path('prototype_teacher', views.prototype_teacher, name="prototype_teacher"),
    path('', views.root, name="roots")
]

kete_hs21/kete_hs21/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('course.urls')),
    path('courses/<int:course_id>/lessons/', include("lesson.urls")),
    path('', include("base.urls")),
]

from django.conf import settings
if settings.DEBUG:
    from django.urls import re_path
    from django.views.static import serve
    urlpatterns.append(re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))

kete_hs21/lesson/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.lessons, name="lessons"),
    path("create", views.create, name="lessons_create"),
    path("details", views.details, name="lessons_details"),
    path("<int:lesson_id>/delete", views.delete, name="lessons_delete"),
    path("<int:lesson_id>/subtitles", views.subtitles, name="lessons_subtitles"),
]

kete_hs21/course/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.core.validators import FileExtensionValidator

from base.models import Profile


class Course(models.Model):
    name = models.CharField(max_length=256, unique=True)
    description = models.TextField(null=True, blank=True, max_length=2048, verbose_name="Beschreibung")
    tags = TaggableManager(blank=True)
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")
    date_modified = models.DateTimeField(auto_now_add=True, verbose_name="Angepasst am")
    created_by = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="course_created_by", verbose_name="erstellt von")
    responsible_teachers = models.ManyToManyField(Profile, through="CourseResponsibleTeachers", related_name="course_responsible_teacher", verbose_name="Verantwortliche Dozenten")
    subscribed_students = models.ManyToManyField(Profile, through="CourseSubscribedStudents", related_name="course_subscribed_students", verbose_name="Eingeschriebene Studenten")


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, max_length=2048, verbose_name="Beschreibung")
    tags = TaggableManager(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now_add=True)


class CourseResponsibleTeachers(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Profile, on_delete=models.CASCADE)


class CourseSubscribedStudents(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Profile, on_delete=models.CASCADE)


class Recording(models.Model):
    recording_name = models.CharField(max_length=256, blank=True)
    recording_description = models.TextField(null=True, max_length=2048, verbose_name="Beschreibung", blank=True)
    recording_tags = TaggableManager(blank=True)
    recording_file = models.FileField(verbose_name="Aufnahme", default=None, blank=True)
    recording_video_archived_name = models.CharField(max_length=256, blank=True)
    recording_audio_archived_name = models.CharField(max_length=512, blank=True)
    recording_text_archived_name = models.CharField(max_length=512, blank=True)
    recording_text_json_archived_name = models.CharField(max_length=512, blank=True)
    recording_audio_split_task_status = models.CharField(max_length=256, blank=True)
    recording_audio_to_text_task_status = models.CharField(max_length=256, blank=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)


class Slideshow(models.Model):
    slideshow_name = models.CharField(max_length=256, blank=True)
    slideshow_tags = TaggableManager(blank=True)
    slideshow_file = models.FileField(verbose_name="Foliensatz", default=None, blank=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

kete_hs21/lesson/models.py
from django.db import models

# Create your models here.

kete_hs21/lesson/forms.py
from django import forms
from django.forms import TextInput, FileInput

from course.models import Lesson, Recording, Slideshow

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ("name", "description", "tags")


class RecordingForm(forms.ModelForm):
    class Meta:
        model = Recording
        fields = ("recording_name", "recording_description", "recording_tags", "recording_file")
        widgets = {'recording_file': FileInput(attrs={'accept': 'video/mp4,video/x-msvideo,video/mpeg,video/ogg,video/webm,'})}

class SlideshowForm(forms.ModelForm):
    class Meta:
        model = Slideshow
        fields = ("slideshow_name", "slideshow_tags", "slideshow_file")

kete_hs21/lesson/views.py
import uuid
import re
from os import path
import threading
import logging

import requests

from .webvtt_utils import create_vtt_from_azure_output, create_json_vtt_from_azure_output

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import JsonResponse

from course.models import Course, Lesson, Recording
from lesson.forms import LessonForm, RecordingForm, SlideshowForm


logger = logging.getLogger(__name__)

@login_required
def lessons(request, course_id):
    corresponding_course = get_object_or_404(Course, id=course_id)
    corresponding_lessons = Lesson.objects.filter(course=corresponding_course)
    context = {
        "recordings_url": settings.RECORDINGS_URL,
        "lessons": corresponding_lessons,
        "course": corresponding_course,
        "is_teacher": request.user.groups.filter(name="teachers").exists()
    }
    return render(request=request, template_name="lesson/lessons.html", context=context)


@login_required()
def delete(request, course_id, lesson_id, needs_redirect=False):
    obj = get_object_or_404(Lesson, id=lesson_id)
    obj.delete()
    if needs_redirect:
        return redirect(lessons)
    return redirect(lessons, course_id)


@login_required()
def subtitles(request, course_id, lesson_id):
    lesson = get_object_or_404(Lesson, id=lesson_id)
    recording = Recording.objects.filter(lesson=lesson)
    if not recording:
        return JsonResponse({"error": "Diese Lektion hat keine Aufnahme."}, status=404)
    try:
        with open(recording.recording_text_json_archived_name, "r") as subtitles_file:
            vtt_content = subtitles_file.read()
    except FileNotFoundError:
        return JsonResponse({"error": "Das VTT-File für diese Aufnahme konnte nicht gefunden werden."})
    except IOError:
        return JsonResponse({"error": "Das VTT-File für diese Aufnahme konnte nicht geöffnet werden."})
    json_response = {
        "lesson_id": lesson.id,
        "recording_id": recording.id,
        "subtitles": vtt_content
    }
    return JsonResponse(json_response)


def write_uploaded_file_to_storage(upload_file, upload_name):
    with open(path.join(settings.RECORDINGS_ROOT, upload_name), 'wb+') as destination:
        for chunk in upload_file.chunks():
            destination.write(chunk)


def create_audio_track_from_video(recording_object_id):
    import subprocess
    logger.warning(f"Starting create_audio_track_from_video for recording id {recording_object_id}")
    recording = Recording.objects.get(pk=recording_object_id)
    recording.recording_audio_split_task_status = "in progress"
    recording.save()
    ffmpeg_command = [f"{settings.FFMPEG_PATH}", "-i", f"{settings.RECORDINGS_ROOT}/{recording.recording_video_archived_name}",
                      "-ar", "16000", "-b:a", "256k", "-vn", f"{settings.RECORDINGS_ROOT}/{recording.recording_audio_archived_name}"]
    ffmpeg_command_result = subprocess.run(ffmpeg_command, stderr=subprocess.DEVNULL)
    if ffmpeg_command_result.returncode != 0:
        logger.warning(f"ffmpeg failed ({ffmpeg_command}) with result {ffmpeg_command_result}")
        recording.recording_audio_split_task_status = "error"
        recording.save()
        return
    recording.recording_audio_split_task_status = "completed"
    recording.save()
    logger.info(f"Finished create_audio_track_from_video for recording id {recording_object_id}")
    translate_audio_to_text(recording_object_id=recording_object_id)


def fetch_azure_tts_api_token(tts_token_url, tts_token_key):
    headers = {
        'Ocp-Apim-Subscription-Key': tts_token_key
    }
    response = requests.post(tts_token_url, headers=headers)
    return str(response.text)


def upload_audio_data_as_blob(audio_file_path,
                              blob_name,
                              storage_account_container_url,
                              storage_account_sas_query_string):
    if not storage_account_container_url.endswith("/"):
        storage_account_container_url += "/"
    if not storage_account_sas_query_string.startswith("?"):
        storage_account_sas_query_string = "?" + storage_account_sas_query_string
    blob_url = storage_account_container_url + blob_name + storage_account_sas_query_string
    headers = {"x-ms-blob-type": "BlockBlob"}
    with open(audio_file_path, "rb") as audio_file:
        result = requests.put(url=blob_url, data=audio_file, headers=headers)
    if result.status_code > 299:
        raise ValueError(f"Failed to upload blob, status {result.status_code} ({result.text})")
    return blob_url


def initiate_speech_to_text_translation(audio_blob_url, tts_api_key):
    headers = {"Content-type": "application/json",
               "Ocp-Apim-Subscription-Key": tts_api_key}
    body = {
        "contentUrls": [
            audio_blob_url
        ],
        "properties": {
            "wordLevelTimestampsEnabled": True,
            "timeToLive": "PT1H",
            "channels": [0]
        },
        "locale": "de-DE",
        "displayName": "Speech to text"
    }
    tts_api_url = f"https://northeurope.api.cognitive.microsoft.com/speechtotext/v3.0/transcriptions"
    result = requests.post(url=tts_api_url, json=body, headers=headers)
    if result.status_code > 299:
        raise ValueError(f"Failed during speech to text translation (status {result.status_code}): {result.text}")
    transcript_url = result.json().get("self")
    logger.info(f"Transcript url is {transcript_url}")
    return transcript_url


def fetch_transcript_content(transcript_url, tts_api_key):
    #try to fetch transcript until its done or we give up ...
    from time import sleep
    run = 0
    transcript_content_url = None
    while run < 60:
        run += 1
        headers = {"Ocp-Apim-Subscription-Key": tts_api_key}
        transcription_hint_url = f"{transcript_url}/files"
        hints_result = requests.get(url=transcription_hint_url, headers=headers)
        for hint in hints_result.json().get("values"):
            if hint.get("kind") == "Transcription":
                transcript_content_url = hint.get("links").get("contentUrl")
                break
        else:
            sleep(10)
    transcript_response = requests.get(transcript_content_url)
    return transcript_response.json()


def write_transcript_to_file(transcript, transcript_file_path):
    import json
    with open(transcript_file_path, "w") as transcript_file:
        json.dump(transcript, transcript_file)


def _deprecated_fetch_via_azure_speech_to_text_api(tts_api_url, tts_api_key, audio_file_path):
    #Cant use this since azure doesnt do audio > 60 sec for this api ...
    api_parameters = {"language": "de-DE",
                      "profanity": "raw", #life is too short for censorship
                      "format": "detailed",
                      "initialSilenceTimeoutMs": "60000",
                      "endSilenceTimeoutMs": "60000"}
    try:
        bearer_token = fetch_azure_tts_api_token(tts_token_url=settings.AZURE_TTS_TOKEN_URL,
                                                 tts_token_key=tts_api_key)
    except (requests.HTTPError, requests.ConnectionError) as err:
        raise ValueError(f"Failed to authenticate with azure (cannot fetch bearer token): {err}")
    try:
        with open(audio_file_path, 'rb') as audio_file:
            response = requests.post(url=tts_api_url,
                                     data=audio_file,
                                     headers={"Content-type": "audio/wav",
                                              "Accept": "application/json",
                                              "Authorization": f"Bearer {bearer_token}"},
                                     params=api_parameters)
    except FileNotFoundError:
        raise ValueError(f"Failed to find audiofile ({audio_file_path})")
    except IOError:
        raise ValueError(f"Failed to read from audiofile ({audio_file_path})")
    except (requests.HTTPError, requests.ConnectionError) as err:
        raise ValueError(f"Failed to translate audio to text for file {audio_file_path}: {err}")
    return str(response.text)


def details(request, course_id):
    corresponding_course = get_object_or_404(Course, id=course_id)
    lessons_of_course = Lesson.objects.filter(course=corresponding_course)
    recordings_of_lessons = Recording.objects.filter(lesson__in=lessons_of_course)
    recordings_in_progress_tts = recordings_of_lessons.filter(recording_audio_to_text_task_status='in progress')
    recordings_in_progress_split = recordings_of_lessons.filter(recording_audio_split_task_status='in progress')
    recordings_in_error_split = recordings_of_lessons.filter(recording_audio_split_task_status='error')
    recordings_in_error_tts = recordings_of_lessons.filter(recording_audio_to_text_task_status='error')
    recordings_in_completed = recordings_of_lessons.filter(recording_audio_to_text_task_status='completed')

    response_dict = {
        "split_in_progress": [recording.lesson.id for recording in recordings_in_progress_split],
        "tts_in_progress": [recording.lesson.id for recording in recordings_in_progress_tts],
        "split_in_error": [recording.lesson.id for recording in recordings_in_error_split],
        "tts_in_error": [recording.lesson.id for recording in recordings_in_error_tts],
        "completed": [recording.lesson.id for recording in recordings_in_completed]
    }
    return JsonResponse(response_dict)


def translate_audio_to_text(recording_object_id):
    recording = Recording.objects.get(pk=recording_object_id)
    if not recording:
        logger.warning(f"Error before audio translation: recording with id {recording_object_id} does not exist")
    recording.recording_audio_to_text_task_status = "in progress"
    recording.save()
    try:

kete_hs21/lesson/templates/lesson/lessons.html
{% extends "base/base.html" %}

{% block title %}Courses{% endblock %}

{% block head %}
<link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
{% endblock %}

{% block content %}
{% load static %}
<div class="d-block align-items-stretch bg-transparent mx-3" style="width: 380px; height: 1200px; margin-top:100px">
    <a class="d-block align-items-center link-dark text-decoration-none text-center">
      <span class="fs-5 fw-semibold">Verfügbare Lektionen: {{ course.name }}</span>
    </a>
    <div class="list-group list-group-flush scrollarea">
      {% for lesson in lessons %}
        <div class="lesson-container list-group-item list-group-item-action border-0 mt-3 rounded-3"
             lesson_id="{{ lesson.id }}"
             recordings_url="{{ recordings_url }}"
             recording_video_archived_name="{{ lesson.recording_set.first.recording_video_archived_name|default_if_none:'nothing' }}"
             recording_text_archived_name="{{ lesson.recording_set.first.recording_text_archived_name|default_if_none:'nothing' }}">
            <div class="w-100 d-flex flex-column">
                <div class="d-inline-flex flex-row flex-nowrap py-2">
                    <h5 class="col-6 flex-fill">{{ lesson.name }}</h5>
                    <small class="flex-fill col-6 ms-auto">{{ lesson.date_created }}</small>
                </div>
                <div class="d-inline-flex flex-row flex-nowrap">
                    <p class="col-7 lesson-description">{{ lesson.description }}</p>
                    <svg width="30" height="30" class="d-inline col-1 lesson-recording-error-icon d-none">
                        <image xlink:href="{% static 'images/error-icon.svg' %}" class="" width="30" height="30"/>
                    </svg>
                    <svg width="30" height="30" class="d-inline col-1 lesson-recording-icon d-none">
                        <image xlink:href="{% static 'images/recording-icon.svg' %}" class="" width="30" height="30"/>
                    </svg>
                    <div class="lesson-recording-status d-inline-flex col-5 d-none">
                        <small class="mx-2 lesson-recording-status-text">STATUS TEXT</small>
                        <div class="col-9 spinner-border text-info" role="status"></div>
                    </div>
                    {% if is_teacher %}
                    <a href="{% url 'lessons_delete' course_id=course.id lesson_id=lesson.id %}" class="btn btn-primary bg-warning text-dark border-0 col-3 ms-auto">Löschen</a>
                    {% endif %}
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
</div>

<div class="d-inline-block w-75 justify-content-start" style="margin-top:150px">
    <div class="d-flex flex-nowrap flex-column" style="width: 66%">
        <div class="video-container flex-fill ml-5">
        <video  id="videojs-player" width="auto" height="auto" class="video-js vjs-fill rounded-3 d-none" controls preload="auto"></video>
        </div>
        <div id="subtitles-container" class="d-flex flex-row mt-3 d-none">
            <div class="card w-100">
              <ul class="list-group list-group-flush">
                  <li class="list-group-item border-0">
                    <textarea id="subtitle-current" class="border-0 w-100 fs-6" rows="3" readonly contenteditable="false" style="resize: none;"></textarea>
                  </li>
                  <li class="list-group-item border-0">
                    <textarea id="subtitle-previous" class="border-0 w-100 fs-6" rows="3" readonly contenteditable="false" style="resize: none;"></textarea>
                  </li>
              </ul>
            </div>
            <div class="d-flex flex-column justify-content-evenly mx-3">
                <button class="btn btn-lg btn-outline-dark mb-3" type="button" title="Dozenten zu diesem Abschnitt anfragen." data-bs-toggle="modal" data-bs-target="#teacher-request">
                    <svg xmlns="http://www.w3.org/2000/svg" width="38" height="38" fill="currentColor" class="bi bi-bookmark-star" viewBox="0 0 16 16">
                      <path d="M7.84 4.1a.178.178 0 0 1 .32 0l.634 1.285a.178.178 0 0 0 .134.098l1.42.206c.145.021.204.2.098.303L9.42 6.993a.178.178 0 0 0-.051.158l.242 1.414a.178.178 0 0 1-.258.187l-1.27-.668a.178.178 0 0 0-.165 0l-1.27.668a.178.178 0 0 1-.257-.187l.242-1.414a.178.178 0 0 0-.05-.158l-1.03-1.001a.178.178 0 0 1 .098-.303l1.42-.206a.178.178 0 0 0 .134-.098L7.84 4.1z"></path>
                      <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"></path>
                    </svg>
                </button>
                <button class="btn btn-lg btn-outline-dark mb-3" type="button" title="Diskussion zu diesem Abschnitt starten.">
                    <svg xmlns="http://www.w3.org/2000/svg" width="38" height="38" fill="currentColor" class="bi bi-chat-dots" viewBox="0 0 16 16">
                        <path d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"></path>
                        <path d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z"></path>
                    </svg>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="d-block mx-2" style="margin-top:150px; width: 15%">
    <div class="d-flex flex-column">
        <image src="{% static 'images/slide1.png' %}" width="auto" height="auto" class="py-2"/>
        <image src="{% static 'images/slide2.png' %}" width="auto" height="auto" class="py-2"/>
        <image src="{% static 'images/slide3.png' %}" width="auto" height="auto" class="py-2"/>
        <image src="{% static 'images/slide4.png' %}" width="auto" height="auto" class="py-2"/>
    </div>
</div>


<div class="modal fade" id="teacher-request" tabindex="-1" aria-labelledby="teacher-request-label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="teacher-request-label">Neue Anfrage</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Dozenten:</label>
            <input type="text" class="form-control" id="recipient-name" readonly>
          </div>
          <div class="mb-3">
            <label for="video-timestamp" class="col-form-label">Abschnitt:</label>
            <input type="text" class="form-control" id="video-timestamp" readonly>
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Anfrage:</label>
            <textarea class="form-control" rows="5" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Schliessen</button>
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Senden</button>
      </div>
    </div>
  </div>
</div>


<script src="https://vjs.zencdn.net/7.17.0/video.min.js"></script>
<script>

var teacher_request_modal = document.getElementById('teacher-request');
teacher_request_modal.addEventListener('show.bs.modal', function (event) {
    var current_subtitles = $("#subtitle-current").html();
    var button = event.relatedTarget;
    var recipient = "{% for responsible_teacher in course.responsible_teachers.all %}@{{ responsible_teacher }} {% endfor %}";
    var modalTitle = teacher_request_modal.querySelector('.modal-title');
    var modalRecipient = teacher_request_modal.querySelector('.modal-body input');
    var modalRequest = teacher_request_modal.querySelector('.modal-body textarea');
    var modalTimestamp = teacher_request_modal.querySelector('#video-timestamp');

   let player = videojs('videojs-player');
    current_video_timestamp_secs = player.currentTime();
    var date = new Date(null);
    date.setSeconds(current_video_timestamp_secs);
    var current_video_timestamp = date.toISOString().substr(11, 8);

    modalTitle.textContent = 'Neue Anfrage an ' + recipient;
    modalRecipient.value = recipient;
    if (current_subtitles.length > 0) {
        modalRequest.value = "Was ist mit: \"" + current_subtitles + "\" gemeint?";
    } else {
        modalRequest.value = "";
    }
    modalTimestamp.value = current_video_timestamp;
});

(function poll_details() {
  $.get('{% url 'lessons_details' course_id=course.id %}', function(data) {
   for (var completed_lesson_id of data.completed) {
         	$("[lesson_id=" + completed_lesson_id + "]").each(function() {
         	    $(this).find(".lesson-recording-icon").removeClass("d-none");
                $(this).find(".lesson-description").removeClass("d-none");
         	    $(this).find(".lesson-recording-status").addClass("d-none");
         	});
   }
   for (var in_progress_lesson_id of [...data.split_in_progress, ...data.tts_in_progress]) {
         	$("[lesson_id=" + in_progress_lesson_id + "]").each(function() {
         	    $(this).find(".lesson-description").addClass("d-none");
         	    $(this).find(".lesson-recording-status").removeClass("d-none");
         	    $(this).find(".lesson-recording-status-text").html("Aufnahme wird verarbeitet...");
         	});
   };
   for (var in_error_lesson_id of [...data.split_in_error, ...data.tts_in_error]) {
         	$("[lesson_id=" + in_error_lesson_id + "]").each(function() {
         	    $(this).find(".lesson-recording-error-icon").removeClass("d-none");
         	});
   };
   setTimeout(poll_details, 7000);
  });
})();


$(".lesson-container").each(function() {
    $( this ).click(function() {
        $(".lesson-container").each(function() {
            $( this ).attr("aria-current","false")
            $( this ).removeClass("active");
        });
         //in case we need to reinitialize -> the old player must be destroyed first for the next vid to load
         if ( videojs.getAllPlayers().length > 0 ) {
            var oldPlayer = document.getElementById('videojs-player');
            videojs(oldPlayer).dispose();
            $(".video-container").append('<video  id="videojs-player" width="auto" height="auto" class="video-js vjs-fill rounded-3 d-none" controls preload="auto"></video>');
         }

        $(this).addClass("active");
        $(this).attr("aria-current","true")
        $("#videojs-player").removeClass("d-none");

        if(! $(this).attr("recording_video_archived_name")) {
            var html_template =`<div class="alert alert-warning" role="alert">Keine Aufzeichnung hinterlegt.</div>`;
            $(".video-container").append(html_template);
            return;
        }
        var video_path = $(this).attr("recordings_url") + "/" + $(this).attr("recording_video_archived_name");
        var subtitles_path = $(this).attr("recordings_url") + "/" + $(this).attr("recording_text_archived_name");

        let captionOptions = {
            kind: 'metadata',
            srclang: 'de',
            label: 'Deutsch',
            src: subtitles_path
        };

        let videoOptions = {
                controls: true,
                autoplay: false,
                fluid: true,
                preload: 'auto',
                sources: [{
                  src: video_path,
                  type: 'video/mp4'
                }]
        };

        let player = videojs('videojs-player', videoOptions);
        player.ready(function(){
            player.addRemoteTextTrack(captionOptions);
            $("#subtitles-container").removeClass("d-none");
            const textTrack = player.remoteTextTracks()[0];
            var subtitles_previous = subtitles_current = "";
            var subtitles_current_timestamp = "";
            textTrack.addEventListener('cuechange', () => {
                let activeCue = textTrack.activeCues[0];
                if (activeCue === undefined) {
                    return;
                } else {
                    //clear previous subtitles in case someone doesn't watch the video sequencially, e.g. clicks on the slider
                    if (subtitles_current_timestamp < activeCue.startTime) {
                        subtitles_previous = subtitles_current;
                    } else {
                        subtitles_previous = "";
                    }
                    subtitles_current_timestamp = activeCue.startTime;
                    subtitles_current = activeCue.text;
                    $("#subtitle-previous").html(subtitles_previous);
                    $("#subtitle-current").html(subtitles_current);
                }
            })
        });

    });
});


</script>

{% endblock %}